### ISSUE TITLE
NetScaler UNKNOWN - 501 Protocol scheme 'proxyname' is not supported

### ISSUE THREAD

**Issue by Rivalld** [slauger/check_netscaler#103]
Hello

How can i use a proxy to connect to my Netscaler?

I can't find the syntax to specify my proxy or to bypass it?

Is there a possibility?

Thanks

**Comment by slauger** [comment]
Hi,

this plugin is based on Perl:LWP. LWP recognizes the normal `http_proxy`, `https_proxy` and `no_proxy` settings. Just export the environment variables and that's it!

Cheers.

**Comment by Rivalld** [comment]
Thanks for the quick response :)

I had `http_proxy `and `https_proxy` setup wrong.
Now it works

Thanks alot and have a nice day!
