### ISSUE TITLE
Support for servicegroups in 12.0

### ISSUE THREAD

**Issue by slauger** [slauger/check_netscaler#14]
See latest commit in branch development (08e84bd99b2ee49a62242a5a5a3b16bf7e8a4781).

Needs some testing, after that the fix could be merged into master.

**Comment by MarcoSchmitz** [comment]
I had the same problem so I changed the property name to "servicegroupeffectivestate". I made some tests in our dev-stage and verified this one as the decisive property. For us it work fine.

**Comment by slauger** [comment]
The problem is that this might break a check against a 10.5, 11.0 and 11.1 firmware. The API for servicegroups was changed in nearly every minor/major release. Citrix has horrible API developers. :(
I need to test this a least against a 11.0 and a 11.1 build, but I hadn't time to prepare a new environment for this. Maybe I have access to a 11.1 NetScaler tomorrow.

**Comment by slauger** [comment]
Fixed in v1.1.1.

**Comment by slauger** [comment]
#19 adds an enhanced check for service groups. I will close this issue.
