### ISSUE TITLE
NTP connectivity

### ISSUE THREAD

**Issue by slauger** [slauger/check_netscaler#18]
Monitoring check for NTP connectivity and time sync status.

**Comment by slauger** [comment]
The command `ntpstatus` from the NITRO API only returns the output of `ntpq -q`. I don't like the idea of reinventing the wheel and parsing the ntpq output.

```
./check_netscaler.pl -H 185.63.131.140 -s -u slauger -p IP23k6n8 -C debug -o ntpstatus -e config"
$VAR1 = {
          'errorcode' => 0,
          'severity' => 'NONE',
          'ntpstatus' => {
                           'response' => '     remote           refid      st t when poll reach   delay   offset  jitter
==============================================================================
*dc01.tmxlab.loc 80.153.195.191   2 u  593 1024  377    0.993   -4.330  11.288
'
                         },
          'message' => 'Done'
        };
```
NTP synchronization can also be checked trough `check_ntp_time`, so this has no priority. Maybe Citrix will changed this in the future of the NITRO API.

**Comment by bb-Ricardo** [comment]
The problem with check_ntp_time is that the default ntp config in NetScaler doesn't allow query. To check NTP you always have to change /nsconfig/ntp.conf manually.

**Comment by bb-Ricardo** [comment]
curently working on this one. Hopefully done by tomorrow.
