### ISSUE TITLE
Performance data 

### ISSUE THREAD

**Issue by nicoh88** [slauger/check_netscaler#2]
Performance data for check_mk would be cool.

![bildschirmfoto 2016-03-24 um 11 46 27](https://cloud.githubusercontent.com/assets/264264/14014992/4ceb08da-f1b6-11e5-97c7-9270245e220d.jpg)

**Comment by slauger** [comment]
Thanks for your feedback. I've already planned to integrate the perfomance data feature in the next release. This is truly one of the most important things for nagios plugins. ;)

**Comment by slauger** [comment]
Performance Data for check_vserver and check_threshold is now available (master branch, latest commit).

**Comment by slauger** [comment]
By the way, the plugin uses the Perl Nagios Libary, so you could use "--extra-opts" to store the NetScaler credentials in an extra *.ini file instead of in the nagios configuration directly.

e.g.
```
define command {
  command_name check_netscaler_vserver
  command_line $USER5$/3rdparty/check_netscaler/check_netscaler.pl -H $HOSTADDRESS$ --extra-opts=netscaler@$USER11$/plugins.ini -C check_vserver -I '$ARG1$'
}
```

```
[netscaler]
username=foo
password=bar
```
