### ISSUE TITLE
Check if a system software update is available

### ISSUE THREAD

**Issue by slauger** [slauger/check_netscaler#23]
Since NetScaler 12.0 there is a update check in the admin GUI.

<img width="548" alt="nsversion" src="https://user-images.githubusercontent.com/8333300/29431398-1d33d2e6-8398-11e7-9b7c-ee5a1f0f1a42.png">

I couldn't find any API method for this. I tried to reverse engineer the PHP code on the appliance to understand how the check works, but I couldn't find anything yet. 

We need some kind of API from Citrix to get the latest version for a specific release (10.5, 11.0, 11.1, 12.0). This would be helpful for a lot of my customers.

An other possible resource to get the latest available version is the RSS feed from Citrix. But well, this might be not the best solution):

- https://www.citrix.com/content/citrix/en_us/downloads/netscaler-adc.rss

This would be cool for other products as well (XenMobile, XenDesktop, ...).

**Comment by bb-Ricardo** [comment]
is it possible that this check is done on the client side. So the browser queries for possible available updates?

**Comment by slauger** [comment]
That's just what I was thinking, but I couldn't find anything yet. I also played around with Wireshark and TamperData some time ago.

**Comment by slauger** [comment]
Parsing the RSS feed works so far, but I don't want to add XML dependencies (e.g. XML::Simple) to check_netscaler. I created a new plugin (check_nsupdate) for this use case.

https://github.com/slauger/check_nsupdate

Closed.
