### ISSUE TITLE
perf_enabled template doesn't exist

### ISSUE THREAD

**Issue by rgevaert** [slauger/check_netscaler#36]
Hi,

Can you provide the perf_enabled template as we are referring to it, but it doesn't exist...

thanks

**Comment by slauger** [comment]
Hi,

unfortunately i do not have a running Icinga 2 setup. The examples for Icinga 2 were a contribution by @bb-Ricardo.

@bb-Ricardo: maybe you could help us here?

**Comment by slauger** [comment]
The missing template is now available in the master branch.
