### ISSUE TITLE
NetScaler CRITICAL - state: no VPNvServer found in configuration

### ISSUE THREAD

**Issue by derry43** [slauger/check_netscaler#79]
I am able to connect successfully to our netscaler using check_netscaler and can query license, interface, hwinfo successfully. However we have two Citrix Gateway virtual servers, which as far as I can see are VPN virtual servers on VPNvServer in check_netscaler terms, however, when we try to get state info for these, we just get the error "NetScaler CRITICAL - state: no VPNvServer found in configuration".

The command we are using is:
.../check_netscaler.pl -H X.X.X.X --username=someone --password=difficult --command=status --objecttype=VPNvServer -ssl

we have also tried specifying the object name with no luck.

.../check_netscaler.pl -H X.X.X.X --username=someone --password=difficult --command=status --objecttype=VPNvServer --objectname="_XD_Netscaler Gateway" --ssl

**Comment by derry43** [comment]
Found the answer to my own issue, looks like it is case sensitivity.

**Comment by slauger** [comment]
Easy. :)

FYI, the `status` check of a vpnvserver will always be UP (if the vServer has bound a a certificate) - independently from the status of the STA servers. So don't forget to also configure a check for `staserver`.
