### ISSUE TITLE
Check the expiry date of a local license file

### ISSUE THREAD

**Issue by hampe4460** [slauger/check_netscaler#83]
Hi,
it's for sure not the right way to post this here, but I don't know another way.
Even if I do the configuration as you wrote in your README, I don't get the check for the license files running with another user than nsroot. With nsroot ev. is working properly.

Always get this error --> NetScaler UNKNOWN - { "errorcode": 2138, "message": "Not authorized to execute this command [show system file -fileLocation \"\/nsconfig\/license\"]", "severity": "ERROR" }

I tried already to set the "add system cmdPolicy" command with user nagios and the effective user I use in the commend line.
I am using the newest Version: v1.6.1

Thanks in advance

**Comment by slauger** [comment]
It seems that the cmdPolicy in the `README.md` does no longer work. I did a quick test and it is sufficent to grant read permissions to the `system` command for the license check.

```
add system cmdPolicy nagios_custom ALLOW "(^show\\s+system\\s+\\S+)|(^show\\s+system\\s+\\S+\\s+.*)"
```

This can be combined with the global (predefined) `read-only` policy for the other checks.

<img width="567" alt="Bildschirmfoto 2021-07-10 um 22 00 07" src="https://user-images.githubusercontent.com/8333300/125175154-735c3c00-e1ca-11eb-9f7e-4d353bc56ef5.png">
