### ISSUE TITLE
LWP will support htt..."

### ISSUE THREAD

**Issue by Baanor** [slauger/check_netscaler#9]
Hello,

I'm trying to supervise our Netscaler and i run into a little problem.
When i try to check Memory (and everything else) i obtain this error with or without ssl option:

> malformed JSON string, neither array, object, number, string or atom, at character offset 0 (before "LWP will support htt...") at Nitro.pm line 70.

We use a NetScaler Virtual Appliance, and the certificate isn't verified.
And this is the versions of the library:

> perl-JSON-2.59-2
perl-libwww-perl-6.05-2
perl-Nagios-Plugin-0.36-9.1

If you have any idea ? 

Thanks.

**Comment by slauger** [comment]
Hi Banner,

I'll have a look at this as soon as possible and get back to you. This might be a bug in the latest commit for the master branch, which added the ssl support.

**Comment by slauger** [comment]
Please give it a try. Thanks for the feedback!

For SSL connections please also install perl-LWP-Protocol-https (documentation is updated).

**Comment by Baanor** [comment]
You're awesome,  it did the job!

Many thanks!

**Comment by slauger** [comment]
$plugin->opts->ssl was a string instead of a bool prior to v1.0.0. This is no longer the case.
